//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task12.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tovar
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string price { get; set; }
        public string description { get; set; }
        public string url { get; set; }
    }
}
